title: Suvid Singhal
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "suvid"
  email: "suvidsinghal@gmail.com"
  url: "https://suvid.dev"

baseurl: 

source: .
destination: ./docs
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : suvid
year : "2021"
